stages:
  - test
  - deploy

test:
  stage: test
  image: node:18
  script:
    - echo "Voici les dossiers que je vois à la racine du projet :"
    - ls -la
    # - cd nom_du_dossier (on le mettra plus tard quand on sera sûr)
    # - npm install
    # - npm test