stages:
  - test
  - deploy

test:
  stage: test
  image: node:18
  script:
    - cd  p2b/backend/
    - npm install
    - npm test

deploy:
  stage: deploy
  only:
    - main
  image: docker
  script:
    - echo "Déploiement en cours..."
    - kubectl apply -f deployment.yaml