version: '3.8'

services:
  # 1. Le service de Base de données
  db:
    image: postgres:15-alpine
    container_name: etnair_db
    restart: always
    environment:
      POSTGRES_USER: etnair_user
      POSTGRES_PASSWORD: etnair_pass
      POSTGRES_DB: etnair_db
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - etnair_network

  # 2. Le service API (Node.js)
  api:
    build: ./api
    container_name: etnair_api
    restart: always
    environment:
      DB_HOST: db
      DB_USER: etnair_user
      DB_PASSWORD: etnair_pass
      DB_NAME: etnair_db
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - etnair_network

# 3. La définition du réseau commun
networks:
  etnair_network:
    driver: bridge
