apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: p2b-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: p2b-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: p2b-api-service
            port:
              number: 3000
